// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef WIDGETPDIAL_h
#define WIDGETPDIAL_h
#include <FL/Fl.H>
#include <FL/Fl_Dial.H>


class WidgetPDial : public Fl_Dial {
    public:
        WidgetPDial(int x,int y, int w, int h, const char *label=0);
        ~WidgetPDial();
        int handle(int event);
        void drawgradient(int cx,int cy,int sx,double m1,double m2);
        void draw();
        void pdialcolor(int r,int g,int b);
        void value_cb2();
        static void value_cb(Fl_Widget*, void*data);
        void tooltip(const char * c);
    private:
        bool textset;
        bool pos;
        double oldvalue;
        class TipWin *tipwin;
};
#endif
