#Find FFTW

find_path(FFTW_INCLUDE_DIR
    NAMES fftw3.h
    PATHS ${FFTW_INCLUDE_DIRS}
    )

find_library(FFTW_LIBRARIES
    NAMES fftw3
    PATHS ${FFTW_LIBRARY_DIRS}
    )

set(FFTW_PROCESS_INCLUDES FFTW_INCLUDE_DIR)
set(FFTW_PROCESS_LIBS FFTW_LIBRARIES)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FFTW DEFAULT_MSG
    FFTW_INCLUDE_DIR FFTW_LIBRARIES)
