#Find MXML

find_path(MXML_INCLUDE_DIR
    NAMES mxml.h
    PATHS ${MXML_INCLUDE_DIRS}
    )

find_library(MXML_LIBRARIES
    NAMES mxml
    PATHS ${MXML_LIBRARY_DIRS}
    )

set(MXML_PROCESS_INCLUDES MXML_INCLUDE_DIR)
set(MXML_PROCESS_LIBS MXML_LIBRARIES)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MXML DEFAULT_MSG
    MXML_INCLUDE_DIR MXML_LIBRARIES)
