#Find Lo

find_path(LIBLO_INCLUDE_DIR
    NAMES lo/lo.h
    PATHS ${LIBLO_INCLUDE_DIRS}
    )

find_library(LIBLO_LIBRARIES
    NAMES lo
    PATHS ${LIBLO_LIBRARY_DIRS}
    )

set(LIBLO_PROCESS_INCLUDES LIBLO_INCLUDE_DIR)
set(LIBLO_PROCESS_LIBS LIBLO_LIBRARIES)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBLO DEFAULT_MSG
    LIBLO_INCLUDE_DIR LIBLO_LIBRARIES)
