#Find PORTAUDIO

find_path(PORTAUDIO_INCLUDE_DIR
    NAMES portaudio.h
    PATHS ${PORTAUDIO_INCLUDE_DIRS}
    )

find_library(PORTAUDIO_LIBRARIES
    NAMES portaudio
    PATHS ${PORTAUDIO_LIBRARY_DIRS}
    )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PORTAUDIO DEFAULT_MSG
    PORTAUDIO_INCLUDE_DIR PORTAUDIO_LIBRARIES)
