#Find MXML

find_path(MXML_INCLUDE_DIRS
    NAMES mxml.h
    PATH_SUFFIXES libmxml4
    PATHS ${MXML_INCLUDE_DIRS}
    )

find_library(MXML_LIBRARIES
    NAMES mxml libmxml mxml_static mxml4 libmxml4 mxml4_static
    PATHS ${MXML_LIBRARY_DIRS}
    )

set(MXML_PROCESS_INCLUDES MXML_INCLUDE_DIRS)
set(MXML_PROCESS_LIBS MXML_LIBRARIES)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MXML DEFAULT_MSG
    MXML_INCLUDE_DIRS MXML_LIBRARIES)
