---
name: Build CI

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC (fltk, disabled)",
            enabled: 1,
            os: windows-latest,
            deps1: "",
            deps2: "",
            testdeps: "",
            info: "",
            # Note: Config "Debug" is fragile on Github Actions - we avoid it here
            # Note: Plugin does not work on MSVC yet - DPF must be updated first
            config: "cmake
                    -B build
                    -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
                    -DRTOSC_WERROR=1
                    -DCMAKE_BUILD_TYPE=RelWithDebInfo
                    -DCMAKE_VERBOSE_MAKEFILE=ON
                    -DPluginEnable=FALSE
                    -DGuiModule=fltk
                    ",
            configext: "cmake -B build -DCompileExtensiveTests=ON ..",
            build: "cmake --build build --config RelWithDebInfo | Tee-Object build.log",
            dump-libs: "Select-String -Path build.log -Pattern '\.lib' | Set-Content linked-libs.txt"
            test: "ctest --output-on-failure --test-dir build -C RelWithDebInfo",
            # re-use build dir, to avoid rebuilding deps with vcpkg
            config-fusion: "cmake
                    -B build
                    -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
                    -DRTOSC_WERROR=1
                    -DCMAKE_BUILD_TYPE=RelWithDebInfo
                    -DCMAKE_VERBOSE_MAKEFILE=ON
                    -DPluginEnable=FALSE
                    -DGuiModule=zest
                    ",
            build-fusion: "cmake --build build --config RelWithDebInfo",
            pack-fusion: "cd build && cpack -G NSIS -C RelWithDebInfo",
            pack-fusion-path: "build/src/zynaddsubfx.exe",
          }
          - {
            name: "MinGW (no-gui + zest)",
            enabled: 1,
            os: ubuntu-latest,
            update: "sudo apt-get update",
            deps1: "sudo apt-get install -y mingw-w64 cmake ninja-build wine64",
            deps2: "./build-mingw-deps $RUNNER_TEMP",
            testdeps: "",
            info: "",
            config: "PKG_CONFIG_PATH=$RUNNER_TEMP/prefix/lib/pkgconfig
                     cmake
                     -S .
                     -B build
                     -G Ninja
                     -DRTOSC_WERROR=ON
                     -DWerror=ON
                     -DCMAKE_VERBOSE_MAKEFILE=ON
                     -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw64.cmake
                     -DMINGW_PREFIX=$RUNNER_TEMP/prefix
                     -DPluginEnable=FALSE
                     -DCMAKE_BUILD_TYPE=Debug
                     -DCompileTests=ON
                     ",
            configext: "cd build && cmake -DCompileExtensiveTests=ON ..",
            build: "cmake --build build",
            # Run tests. There will be warnings "it looks like wine32 is missing, you should install it." and that it could not create a GUI - these can be ignored
            test: "cd build && ctest --output-on-failure",
            config-fusion: "PKG_CONFIG_PATH=$RUNNER_TEMP/prefix/lib/pkgconfig
                            cmake
                            -S .
                            -B build-fusion
                            -G Ninja
                            -DRTOSC_WERROR=ON
                            -DWerror=ON
                            -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw64.cmake
                            -DMINGW_PREFIX=$RUNNER_TEMP/prefix
                            -DPluginEnable=FALSE
                            -DCMAKE_BUILD_TYPE=Release
                            -DGuiModule=zest
                            ",
            build-fusion: "cmake --build build-fusion"
          }
    steps:
      - name: check out
        if: ${{ matrix.config.enabled == 1 }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: update_apt
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.update }}
      - name: install_deps1
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.deps1 }}
      - name: install_deps2
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.deps2 }}
      - name: install_test_deps1
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.testdeps }}
      - name: submodule
        if: ${{ matrix.config.enabled == 1 }}
        run: git submodule update --init --recursive
      - name: info
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.info }}
      - name: create_builddirs
        if: ${{ matrix.config.enabled == 1 }}
        run: mkdir build; mkdir build-fusion
      - name: configure
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.config }}
      - name: configure-extensive
        if: ${{ matrix.config.enabled == 1 && ( (github.event_name == 'pull_request_review' && github.event.action == 'submitted') || ( github.ref == 'refs/heads/master' ) ) }}
        run: ${{ matrix.config.configext }}
      - name: make
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.build }}
      - name: upload linked libs
        uses: actions/upload-artifact@v7
        with:
          name: linked-libraries
          path: linked-libraries.txt
      - name: dumpbin-dependencies
        if: ${{ matrix.config.os == 'windows-latest' }}
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dumpbin /DEPENDENTS build\src\RelWithDebInfo\zynaddsubfx.exe
      - name: make test
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.test }}
      - name: configure-fusion
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.config-fusion }}
      - name: make-fusion
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.build-fusion }}
      - name: objdump-dependencies
        if: ${{ matrix.config.name == 'MinGW (no-gui + zest)' }}
        run: |
          x86_64-w64-mingw32-objdump -p build-fusion/src/zynaddsubfx.exe \
            | grep "DLL Name"
      - name: package-fusion
        if: ${{ matrix.config.enabled == 1 }}
        run: ${{ matrix.config.pack-fusion }}
      - name: upload-artifacts
        if: ${{ matrix.config.enabled == 1 }}
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: ${{ matrix.config.pack-fusion-path }}
