name: dpf

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-x86_64]
        # FIXME linux-riscv64 needs -latomic
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: ${{ matrix.target }}
          dpf_path: 'DPF'
          pawpaw: true

  macos:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: ${{ matrix.target }}
          dpf_path: 'DPF'
          pawpaw: true

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: ${{ matrix.target }}
          dpf_path: 'DPF'
          pawpaw: true

  # FIXME need to be able to specify custom output bin dir
  #pluginval:
    #runs-on: ubuntu-20.04
    #steps:
      #- uses: actions/checkout@v3
        #with:
          #submodules: recursive
      #- uses: distrho/dpf-cmake-action@v1
        #with:
          #target: pluginval
          #dpf_path: 'DPF'
          #pawpaw: true
